### ISSUE TITLE
Unable to continue past starting localhost:4000

### ISSUE THREAD

**Issue by Duke1014** [learn-co-curriculum/phase-4-debugging-network-requests#2]
### Canvas Link

https://learning.flatironschool.com/courses/4689/assignments/138689?module_item_id=287542

### Concern

After using `npm install --prefix client` and `npm start --prefix client` to start running localhost:4000 (README lines 24 - 33), the server immediately fails to compile because of ./src/components/App.js. Full error shown below:

### Additional Context

![image](https://user-images.githubusercontent.com/67128440/143942997-fb16addc-1494-4a7e-add9-965b09692941.png)

The specific error points to `<>` on line 8. 

### Suggested Changes

React Router v6 came out after this was created, so it could be possible that ./src/components/App.js is outdated?

**Comment by ihollander** [comment]
Hi @Duke1014 - thanks for flagging! I'm not able to reproduce the error message you're seeing — when I install the dependencies and start the app, it runs as expected. 

The syntax on line 8 is a [React Fragment](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) which has had support for quite some time now, so I don't believe this is an issue with this lesson specifically. 

There may be some configuration in your editor or local environment (such as globally installed node modules or VS Code extensions) that are causing this issue. If you're encountering this issue other times you use React fragments, I'd suggest disabling extensions in your text editor or reinstalling Node 16 to see if that helps. You can also ask your instructor or use the chat feature in Canvas for more troubleshooting support.
